# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r:
  - release
  - devel

cache: packages

before_install:
  - apt-get update
  - apt-get install -y libcurl4-openssl-dev 
#  - Rscript -e "install.packages('curl')"
# - sudo apt-get install libcurl4-openssl-dev

r_packages:
  - withr
  - covr

after_success:
  - Rscript -e 'covr::codecov(quiet=FALSE)'

notifications:
  email: false